spring.application.name=Students
server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://host.docker.internal:3306/tap}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:password}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
