spring.application.name=jwt

jwt.secret=MySuperSecretKeyForJwtAuthentication123456789
jwt.expiration=3600000
jwt.issuer=secure-api


# env variable for particular session : $env:JWT_SECRET="SUPER_SECRET_KEY_123"
# set JWT_SECRET=SUPER_SECRET_KEY_123
# set JWT_SECRET=my-super-secret-key-my-super-secret-key